GET http://localhost:3000/todos/?status=TO%20DO
GET http://localhost:3000/todos/
GET http://localhost:3000/todos/?date=2021-12-12/
POST http://localhost:3000/todos/

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}

PUT http://localhost:3000/todos/

{ "status": "DONE" }

GET http://localhost:3000/todos/?date=:date'
PUT http://localhost:3000/todos/todoId/
